# Use official Python image

FROM python:3.9-slim



# Set working directory

WORKDIR /app



# Copy all files into container

COPY . /app



# Run the script when container starts

CMD ["python", "app.py"]